name: ClamAV scan

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - develop

jobs:
  ClamAV_Scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub ClamAV Scan
        id: scan
        uses: djdefi/gitavscan@main
        with:
          full: '--full'

      - name: Comment result
        if: steps.scan.outcome == 'failure'
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Scan ${{ steps.scan.outcome }}`
            })
