name: Post Slack

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
      - develop
env:
  LOG_GROUP_NAME: ${{ secrets.LOG_GROUP_NAME }}
  FILTER_PATTERN: ${{ secrets.FILTER_PATTERN }}

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Run AWS Logs
        id: count
        run: aws logs filter-log-events --log-group-name ${{ env.LOG_GROUP_NAME }} --filter-pattern ${{ env.FILTER_PATTERN }} --start-time $(date -d '1 day ago' +%s)000 --end-time $(date +%s)000 --query '*[].message' --output text | tr "\t" "\n" | wc -l

      - name: Notify Result
        if: steps.count.outcome == 'success'
        uses: slackapi/slack-github-action@v1.18
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
            	"blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": " 昨日のカウントは `${{ steps.count.outputs.stdout }}` だったよ"
            			}
            		}
            	]
            }
