name: ClamAV scan

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  Scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Git AV Scan
        id: scan
        uses: djdefi/gitavscan@main
        with:
          full: '--full'

      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Scan ${{ steps.scan.outcome }}`
            })
