name: AWS Command

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
      - develop

jobs:
  aws:
    runs-on: ubuntu-latest
    steps:
      - name: aws version
        run: aws --version
