name: ClamAV scan

on:
  push:
    branches:
      - develop

jobs:
  ClamAV_Scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub ClamAV Scan
        id: scan
        uses: djdefi/gitavscan@main
        with:
          full: '--full'
